name: CI
on: push

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Poetry
        run: python -m pip install --upgrade poetry
      - name: Install Dependencies
        run: poetry install
      - name: Run Tests
        run: poetry run pytest --doctest-modules --doctest-glob="docs/**/*.rst" --cov=./ --cov-report=xml --verbose
      - name: Codecov
        if: github.ref == 'refs/heads/main' # only run for main branch
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: false
  release:
    runs-on: ubuntu-latest
    needs: pytest
    if: github.ref == 'refs/heads/main' # only run for main branch
    steps:
      - name: Checkout Repository
        uses: stjudecloud/release-python-action@v1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          committer-name: "Clay McLeod"
          committer-email: "clay.l.mcleod@gmail.com"
          run-pytest: true
